### ISSUE TITLE
How can I require local file for workers?

### ISSUE THREAD

**Issue by zhaoyao91** [Microsoft/napajs#102]
Say, how can I broadcast such code in workers?

```
const f = require('../lib/my_function')
...
```

**Comment by daiyip** [comment]
If you want to just execute a function from a module, you don't need to broadcast in order to use it. Simply do `zone.execute('../lib/my_module', 'my_function', [args]);`.

Certainly you can do `zone.broadcast('f = require("../lib/my_function");`, which will set `f` in `global`.

**Comment by zhaoyao91** [comment]
The function file requires `object-hash`, which can't be loaded by workers. I don't know why.

**Comment by daiyip** [comment]
Please note that napajs by now doesn't support any node module, since many of Node.js core modules are not supported in Napa.js workers yet. So module that directly or indirectly depends on unsupported Node.js APIs cannot be loaded in workers. 

Please see https://github.com/Microsoft/napajs/blob/master/docs/api/node-api.md

**Comment by zhaoyao91** [comment]
That's quite a big limitation. Anyway, thanks for help.
