### ISSUE TITLE
[BUG] Zone can't execute if the object contains traditional chinese characters

### ISSUE THREAD

**Issue by joseph1125** [Microsoft/napajs#174]
I encounter an auto-quit without throwing any error messages when I try to assign napajs zone to return the input, later, it is discovered that this is due to the object containing traditional chinese characters, once those characters are replaced by english, it no longer happens.

I had included a sample code for your references.

OS: Windows 8.1 64-bit
NodeJS: Node 9.3.0
NapaJS: 0.1.8
[napa-test.zip](https://github.com/Microsoft/napajs/files/1597285/napa-test.zip)

**Comment by fs-eire** [comment]
This is a known issue of string encoding in Napa. Commit b9b1cfd9c7ad78d09bea0aa64b546eb91616077c is the fix to the bug (#153). It will be fixed in the next release.

If you want to unblock yourself asap, you can try [build from source](https://github.com/Microsoft/napajs/wiki/build-napa.js-from-source).

**Comment by fs-eire** [comment]
The latest release fixed this problem. Close the issue.
