### ISSUE TITLE
Unable to complete all tasks

### ISSUE THREAD

**Issue by Lizhooh** [Microsoft/napajs#94]
Can not finish 7 tasks on my computer, sometimes only finished 5, sometimes there will be errors.

![20171023090504](https://user-images.githubusercontent.com/19299088/31868440-8f32ce2a-b7d1-11e7-83e8-4cb5bfe3565d.png)

**nodejs v8.5 win7 x64 i5-4300U**

**Comment by fs-eire** [comment]
This is a combination of 2 issues.

for 1), Assertion failed: \`workerId < _workers.size()`. This has been fixed in #109 and will be included in next patch release.
for 2), Random crash on node 8.5.0 or higher when executing memory consuming js code in napa zone. Same issue to #96. This is also tracked in https://github.com/nodejs/node/issues/16658. We are following this issue.

**Comment by helloshuangzi** [comment]
fixed with https://github.com/Microsoft/napajs/pull/109
